### ISSUE TITLE
Why not use nearend speech s to be the target ?

### ISSUE THREAD

**Issue by xiaoqi91** [adobe-research/MetaAF#18]
Thanks for sharing your excellent work! 
Could you please explain that why not use the clean or noisy nearend speech to be the network target ? And why use the mic signal d be 
 the target can cover double talk scenes ? Thank you.

**Comment by jmcasebeer** [comment]
Thanks for the question.

In the original work, we used the raw microphone signals so that the training was unsupervised, and did not require oracle signals (like clean speech). If you're interested in code and models that use the clean speech for training, check out the other branch [here](https://github.com/adobe-research/MetaAF/tree/ct-meta-af/zoo/sms_af).

**Comment by xiaoqi91** [comment]
> Thanks for the question.
> 
> In the original work, we used the raw microphone signals so that the training was unsupervised, and did not require oracle signals (like clean speech). If you're interested in code and models that use the clean speech for training, check out the other branch [here](https://github.com/adobe-research/MetaAF/tree/ct-meta-af/zoo/sms_af).

Thanks for your quick reply. Looking forward to your new paper!
